186 issues-[instance] remove instance error when wasm file removed
machinefi/w3bstream pull request #227
Opened 2022-11-25 06:44 UTC by hunshenshi

#186

2022-11-25 06:48 UTC, saitofun requested changes

2022-11-25 06:48 UTC, saitofun commented on pkg/modules/deploy/deploy.go
> +				cmd = enums.DEPLOY_CMD__START
when instance load failed cmd should be `DEPLOY_CMD_UNKNOWN`

2022-11-25 06:48 UTC, saitofun commented on pkg/modules/resource/resource.go
> +func CheckResourceExist(ctx context.Context, path string) bool {
Remove this method use `IsPathExist` instead

2022-11-25 06:48 UTC, saitofun commented on pkg/modules/vm/instance_new.go
> +		return status.ExtractFileFailed.StatusErr().WithDesc(err.Error())
Don't need status error

2022-11-25 07:25 UTC, hunshenshi commented on pkg/modules/deploy/deploy.go
> +				cmd = enums.DEPLOY_CMD__START
if cmd still is `DEPLOY_CMD_UNKNOWN`, the instance will can't be started again.
the state `INSTANCE_STATE__LOAD_FAIL` is a error running state,  so the instance should be start again, maybe this time will start right.

2022-11-25 07:25 UTC, hunshenshi commented on pkg/modules/resource/resource.go
> +func CheckResourceExist(ctx context.Context, path string) bool {
`IsPathExist` is not used to be compatible with other file system.

2022-11-25 07:25 UTC, hunshenshi commented on pkg/modules/vm/instance_new.go
> +		return status.ExtractFileFailed.StatusErr().WithDesc(err.Error())
fine

2022-11-29 02:41 UTC, saitofun approved these changes

2022-11-29 09:53 UTC, merged