feat(ratelimit): traffic limit models
machinefi/w3bstream pull request #648
Opened 2023-06-02 08:18 UTC by hunshenshi

add traffic limit db models
#647

2023-06-03 15:59 UTC, saitofun requested changes

2023-06-03 15:59 UTC, saitofun commented on pkg/models/traffic_limit.go
> +	CycleUnit enums.TrafficCycle     `db:"f_cycle_unit"                    json:"cycleUnit"`
should here reserved a `duration` field, and mapping `TrafficCycle` to duration?

2023-06-03 17:17 UTC, saitofun commented
pls install pre-commit
```shell
pip install pre-commit
cd ${w3bstream_repo} && pre-commit install
```

2023-06-05 02:59 UTC, hunshenshi commented on pkg/models/traffic_limit.go
> +	CycleUnit enums.TrafficCycle     `db:"f_cycle_unit"                    json:"cycleUnit"`
`CycleNum` and `CycleUnit` are similar to the meaning of `duration`, the former is more flexible and controllable, and it is more convenient in subsequent calculations , see [pr#649](https://github.com/machinefi/w3bstream/pull/649/files#diff-ea7fdc1a9433f084c324ff96d24a6a85019c47051858b732c952a1d170c74d7cR57)

2023-06-05 03:49 UTC, huangzhiran approved these changes

2023-06-07 07:20 UTC, merged