feat(ratelimit): traffic limit http api
machinefi/w3bstream pull request #650
Opened 2023-06-02 10:35 UTC by hunshenshi

fork from #649  and #648 
issues #647 
add http api for traffic limit

2023-06-02 17:37 UTC, Liuhaai commented
IMO, rate limiting for api would be better to be done at Cloudflare or nginx. Otherwise, how could the requests be limited per IP in the backend?

2023-06-05 01:00 UTC, hunshenshi commented
> IMO, rate limiting for api would be better to be done at Cloudflare or nginx. Otherwise, how could the requests be limited per IP in the backend?

It is possible to set different rates for each project, similar to a billing system.

2023-06-09 08:33 UTC, saitofun requested changes
gen oas manual

2023-06-09 08:33 UTC, saitofun commented on cmd/srv-applet-mgr/apis/middleware/current_user.go
> +		return nil, status.NoTrafficLimitPermission
NoProjectPermission

2023-06-09 08:37 UTC, saitofun approved these changes

2023-06-09 08:53 UTC, merged