feat(blockchain): support monitor pause/start
machinefi/w3bstream pull request #670
Opened 2023-06-19 06:10 UTC by huangzhiran

2023-06-19 16:35 UTC, saitofun requested changes

2023-06-19 16:35 UTC, saitofun commented on cmd/srv-applet-mgr/apis/monitor/put.go
> +		return nil, status.BadRequest
same above

2023-06-19 16:35 UTC, saitofun commented on pkg/modules/blockchain/api_contract.go
>  	n := *r
no need value copy

2023-06-19 16:35 UTC, saitofun commented on pkg/modules/blockchain/api_tx.go
> +	n.Paused = getPaused(n.Paused)
req.EventType default value `enums.MONITOR_EVENTTYPEDEFAULT` otherwise use user assigned value.
req.Paused, datatypes.Bool can only be one of `true`, `false` and `null`, and its default value is `false`.
so no need `getEventType` and `getPaused`

2023-06-19 16:35 UTC, saitofun commented on pkg/modules/blockchain/api_tx.go
> +	expr := builder.Update(tbl).Where(m.ColChainTxID().In(ids)).Set(tbl.AssignmentsByFieldValues(fvs)...)
ref: builder_z_stmt_test.go:L134
```
	expr := builder.Update(d.T(m)).Set(
		m.ColPaused().ValueBy(s),
		m.ColUpdatedAt().ValueBy(time.Now()),
	).Where(m.ColChainTxID().In(ids))
```

2023-06-19 16:35 UTC, saitofun commented on pkg/modules/blockchain/contract.go
> +	cs, err := m.List(d, builder.And(
impl `ListContractLogByCondArgs`?

2023-06-19 16:35 UTC, saitofun commented on pkg/modules/blockchain/tx.go
> +	cs, err := m.List(d, builder.And(m.ColFinished().Eq(datatypes.FALSE), m.ColPaused().Eq(datatypes.FALSE)))
impl `ListChainTxByCondArgs`?

2023-06-19 16:35 UTC, saitofun commented on pkg/modules/blockchain/api_tx.go
> +func UpdateChainTxPausedBySFIDs(ctx context.Context, ids []types.SFID, s datatypes.Bool) error {
BatchUpdate....

2023-06-19 16:35 UTC, saitofun commented on pkg/modules/blockchain/api_height.go
>  	n := *r
no need value copy

2023-06-20 02:31 UTC, hunshenshi approved these changes

2023-06-20 09:14 UTC, huangzhiran commented on pkg/modules/blockchain/contract.go
> +	cs, err := m.List(d, builder.And(
will change at next version

2023-06-21 01:58 UTC, merged